config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/one' #, to: 'pages#index', as: 'paguina_principal'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def one
    end
    def two
    end
    def three
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <nav class = "navbar-inverse">
      <a href="<%= pages_one_path%>">Page One</a>
      <a href="<%= pages_two_path%>">Page Two</a>
      <a href="<%= pages_three_path%>">Page Three</a>
    </nav>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>  
  </body>
</html>

app/views/pages/one.html.erb
<h1>Ricardo Emilio Alvarez Campos</h1>

app/views/pages/three.html.erb
<h2>Page Three</h2>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit nostrum pariatur quas inventore itaque iure sed hic, perferendis libero asperiores esse accusantium molestiae, recusandae odio consectetur perspiciatis! Enim, ad obcaecati?</p>

app/views/pages/two.html.erb
<%= image_tag 'captura_pantalla', size: '1280x720'%>